services:
  backend:
    image: ghcr.io/spikevn/butbase:latest
    container_name: butbase-backend
    restart: always
    ports:
      - "127.0.0.1:6942:6942"
    volumes:
      - ./backend/db_data:/opt/butbase/db_data
      - ./backend/logs:/opt/butbase/logs
    environment:
      - JWT_SECRET_KEY=!!!REPLACEME!!!
      - DEBUG=False

  sqlite-web:
    image: docker.io/coleifer/sqlite-web
    container_name: butbase-sqlite-web
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./backend/db_data:/data:Z
    environment:
      - SQLITE_DATABASE=database.sqlite
    command: sqlite_web -p 8080 -H 0.0.0.0 /data/database.sqlite

  umami:
    image: ghcr.io/umami-software/umami:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      umami-db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  umami-db:
    image: docker.io/postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db-data:
